"""added nickname

Revision ID: 42d4f5b9b98f
Revises: f5ad0332a672
Create Date: 2019-03-15 00:01:20.097499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d4f5b9b98f'
down_revision = 'f5ad0332a672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('_customer_version', sa.Column('nick_name', sa.Unicode(length=255), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('nick_name', sa.Unicode(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'nick_name')
    op.drop_column('_customer_version', 'nick_name')
    # ### end Alembic commands ###
