"""initial build

Revision ID: f5ad0332a672
Revises: 
Create Date: 2019-03-14 23:57:35.237329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ad0332a672'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_address_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('type', sa.Unicode(length=20), autoincrement=False, nullable=True),
    sa.Column('street', sa.Unicode(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.Unicode(length=255), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.Unicode(length=8), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix__address_version_end_transaction_id'), '_address_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix__address_version_operation_type'), '_address_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix__address_version_transaction_id'), '_address_version', ['transaction_id'], unique=False)
    op.create_table('_customer_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_date', sa.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.Unicode(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.Unicode(length=255), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix__customer_version_end_transaction_id'), '_customer_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix__customer_version_operation_type'), '_customer_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix__customer_version_transaction_id'), '_customer_version', ['transaction_id'], unique=False)
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('first_name', sa.Unicode(length=255), nullable=True),
    sa.Column('last_name', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Unicode(length=20), nullable=True),
    sa.Column('street', sa.Unicode(length=255), nullable=True),
    sa.Column('city', sa.Unicode(length=255), nullable=True),
    sa.Column('postal_code', sa.Unicode(length=8), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    op.drop_table('transaction')
    op.drop_table('customer')
    op.drop_index(op.f('ix__customer_version_transaction_id'), table_name='_customer_version')
    op.drop_index(op.f('ix__customer_version_operation_type'), table_name='_customer_version')
    op.drop_index(op.f('ix__customer_version_end_transaction_id'), table_name='_customer_version')
    op.drop_table('_customer_version')
    op.drop_index(op.f('ix__address_version_transaction_id'), table_name='_address_version')
    op.drop_index(op.f('ix__address_version_operation_type'), table_name='_address_version')
    op.drop_index(op.f('ix__address_version_end_transaction_id'), table_name='_address_version')
    op.drop_table('_address_version')
    # ### end Alembic commands ###
